# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d11cdc8159f8b3b51de9b2c39f9ca9547cf4d18cd07eb3789842e24bb151ae51e16b6e96f0c955c4d8a0610c13a727e8291935aa38648d0ff0ab22de68349287

test:
  secret_key_base: d18d1e921dcca110b62d340eba0039a23ad6bf2db99d47321d0bb911a7f8dff6f3f8d2fc49981a79544e5e33c00d7317bd1126cd622d78d6e58eb1bf7cb3c2e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
